openapi: '3.0.3'
info:
  title: 'LEDES API (For illustration only)'
  termsOfService: https://ledes.org/terms-of-use/
  description: |
    This is an illustration of how the OpenAPI specification could be used to document the LEDES API for the [ledes.org](https://ledes.org/ledes-api/).
    It is not complete and field names and enum values have been changed to conform to a different lettercase convention (rather than CamelCase).

    The public githib repo for this site is available on [https://github.com/Apperio/ledes-api-docs](https://github.com/Apperio/ledes-api-docs) where you 
    can see the [yaml](https://github.com/Apperio/ledes-api-docs/blob/master/openapi.yml) file that was used to generate this page.

    The paths defined in the this URL must be relative to a base URL that contains a unique discriminator for that business, within what could potentially be
    a multitenant solution.
  contact:
    email: loc@ledes.org, stephen@apperio.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/api/v1/businesses/{business_id}
    description: The base URL contains a server URL, and an endpoint path that includes a unique identifier for that business, within the vendor platform.
paths:
  /invoices:
    post:
      tags:
        - Invoices
      summary: Submit an invoice
      requestBody:
        description: |
          Send an invoice using one of the existing LEDES file formats (ie. LEDES XML) as a file.

          This is the main method to send an existing LEDES invoice file.
          The LEDES file can be optionally encrypted.
          NOTE: It is already required that all data be encrypted in transit, so this would be additional encryption
          of the LEDES file, which would then require a mechanism for the receiving system to be able to unencrypt
          the LEDES file. If encrypted, the encryption method is part of the system setup. Returns an invoiceID,
          receivedDateTime, and errors (see response below). The invoiceID is used for subsequent API calls to send
          an attachment for the invoice or to get the status of the invoice. The vendor for the invoice should be
          identified by the authentication and checked against the vendor identified within the LEDES files.'
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                invoice:
                  $ref: '#/components/schemas/invoice_post'
                ledesfile:
                  type: string
                  format: binary
              encoding:
                ledesfile:
                  contentType: text/plain, text/csv, application/xml
            example:
              invoice:
                ledes_format: LEDES98BIV2
                encrypted: False
                ledes_filename: Invoice1234.234.xml
                ledes_file_media_type: 'text/csv'
                invoice_type: INVOICE
              ledesfile: '<binary>'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoiceid:
                    $ref: '#/components/parameters/invoiceid'
                  received_time:
                    type: string
                    description: The time the invoice was received.
                    example: '2020-14-19T15:55:12-04:00'
                  invoice_status:
                    $ref: '#/components/schemas/invoice_status'
                example:
                  invoiceid: '4567'
                  received_time: '2020-14-19T15:55:12-04:00'
                  invoice_status: 'RECEIVED'
        '202':
          description: Accepted. Processing not completed yet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoiceid:
                    $ref: '#/components/parameters/invoiceid'
                  received_time:
                    type: string
                    description: The time the invoice was received.
                    example: '2020-14-19T15:55:12-04:00'
                  invoice_status:
                    $ref: '#/components/schemas/invoice_status'
                example:
                  invoiceid: '4567'
                  received_time: '2020-14-19T15:55:12-04:00'
                  invoice_status: 'RECEIVED'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoiceid:
                    $ref: '#/components/parameters/invoiceid'
                  received_time:
                    type: string
                    description: The time the invoice was received.
                    example: '2020-14-19T15:55:12-04:00'
                  invoice_status:
                    $ref: '#/components/schemas/invoice_status'
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        error:
                          type: string
                          example: "Invalid invoice_type : LEDES99B"
        '403':
          description: User does not have permission to post invoices.
        '415':
          description: Unsupported media type. The server does not support this LEDES
            file standard.
        '500':
          description: Internal server error.
  /invoices/{invoiceid}:
    get:
      tags:
        - Invoices
      summary: Get an invoice
      description: Returns a single invoice with status
      parameters:
        - in: path
          name: invoiceid
          schema:
            $ref: '#/components/parameters/invoiceid'
      responses:
        '200':    # status code
          description: OK. Invoice found.
          content:
            application/json:
              schema:
                properties:
                  invoiceid:
                    $ref: '#/components/parameters/invoiceid'
                  vendor_invoice_number:
                    type: string
                    description: The original invoice number specified by the sending system.
                  invoice_status:
                    $ref: '#/components/schemas/invoice_status'
                  invoice_status_time:
                    type: string
                    description: The time the status was set in UTC using ISO 8601.
                    example: '2020-04-19T15:55:12-04:00'
                  rejection_note:
                    type: string
                    description: When an invoice is rejected, this can be used to describe the overall reason for the rejection. Note that the invoiceErrors element holds a more detailed description of each individual error and this element should duplicate that information.
                    example: 'Too many billing guideline violaions.'
                  original_total:
                    type: string
                    description: The original invoice total amount from the vendor. This should be a string of numbers, followed by a decimal place, followed by two numbers. This should always be included unless the LEDES files could not be parsed.
                    example: '55435.00'
                  original_currency:
                    type: string
                    description: The currency for the original invoice total amount from the vendor. This should always be included unless the LEDES files could not be parsed. The three-character ISO-4217 currency code.
                    example: 'USD'
                  approved_total:
                    type: string
                    description: The invoice total amount approved by the client. For jurisdictions where clients can pay less than the originalTotal this is the amount the client plans to pay or has paid. The invoiceAdjustments section below should document the adjustments the client is imposing on the invoice. If the status is Paid, this should also match the invoicePayment data below.
                    example: '35435.00'
                  approved_currency:
                    type: string
                    description: The currency for the approved_total. The three-character ISO-4217 currency code.
                    example: 'USD'
                  invoice_errors:
                    $ref: '#/components/schemas/invoice_errors'
                  adjustments:
                    $ref: '#/components/schemas/invoice_adjustments'
                  payments:
                    $ref: '#/components/schemas/invoice_payments'
        '404':
          description: 'Not found. No invoice with that id.'

  /matter/{client_matter_id}/accruals:
    put:
      parameters:
        - in: path
          name: client_matter_id
          schema:
            type: string
            description: the unique identifier for the matter, according to either client system.
      tags:
        - Accruals
      summary: Update the accruals data for one matter
      description: Proposal - update the accrual figures for a single matter.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accrual_currency:
                  $ref: '#/components/schemas/accrual_currency'
                accrual_net_total:
                  $ref: '#/components/schemas/accrual_net_total'
                fee_accrual_net_total:
                  $ref: '#/components/schemas/fee_accrual_net_total'
                expense_accrual_net_total:
                  $ref: '#/components/schemas/expense_accrual_net_total'
                monthly_accrual_net_totals:
                  type: array
                  description: Optional accruals totals broken down by calendar month.
                  items:
                    $ref: '#/components/schemas/monthly_accrual_net_total'
                line_items:
                  type: array
                  description: Optional individual line item detail for expenses and fees accruals on this matter.
                  items:
                    anyOf:
                      - $ref: '#/components/schemas/Fee'
                      - $ref: '#/components/schemas/Expense'
                    discriminator:
                      propertyName: line_item_type
                      mapping:
                        Fee: '#/components/schemas/Fee'
                        Expense: '#/components/schemas/Expense'
              example:
                accrual_currency: 'USD'
                accrual_net_total: '15600.00'
                fee_accrual_net_total: '10000.00'
                expense_accrual_net_total: '5600.00'
                monthly_accrual_net_totals:
                  - month: '202001'
                    accrual_currency: 'USD'
                    accrual_net_total: '1600.00'
                    fee_accrual_net_total: '1000.00'
                    expense_accrual_net_total: '600.00'
                  - month: '202002'
                    accrual_currency: 'USD'
                    accrual_net_total: '14000.00'
                    fee_accrual_net_total: '9000.00'
                    expense_accrual_net_total: '5000.00'
                line_items:
                  - line_item_number: 45294
                    line_item_type: 'F'
                    line_item_unit_cost: '500.00'
                    line_item_number_of_units: '2'
                    line_item_total: '1000.00'
                    line_item_currency: 'USD'
                    line_item_date: '20200115'
                    line_item_activity_code: 'A101'
                    line_item_task_code: 'L120'
                    line_item_description: 'Planning case'
                    timekeeper_id: 345
                    timekeeper_first_name: 'Lisa'
                    timekeeper_last_name: 'Jones'
                    timekeeper_classsification: 'ASSOC'
                  - line_item_number: 45298
                    line_item_type: 'E'
                    line_item_unit_cost: '10.00'
                    line_item_number_of_units: '60'
                    line_item_total: '600.00'
                    line_item_currency: 'USD'
                    line_item_date: '20200118'
                    line_item_task_code: 'L140'
                    line_item_expense_code: 'X101'
                    line_item_description: 'Printing costs'
                  - line_item_number: 45455
                    line_item_type: 'F'
                    line_item_unit_cost: '500.00'
                    line_item_number_of_units: '7'
                    line_item_adjustment_amount: '-500.00'
                    line_item_total: '3000.00'
                    line_item_currency: 'USD'
                    line_item_date: '20200215'
                    line_item_task_code: 'L310'
                    line_item_activity_code: 'A104'
                    line_item_description: 'Reviewing contract'
                    timekeeper_id: 345
                    timekeeper_first_name: 'Lisa'
                    timekeeper_last_name: 'Jones'
                    timekeeper_classsification: 'ASSOC'
                  - line_item_number: 45458
                    line_item_type: 'F'
                    line_item_unit_cost: '1000.00'
                    line_item_number_of_units: '6'
                    line_item_total: '6000.00'
                    line_item_currency: 'USD'
                    line_item_date: '20200216'
                    line_item_task_code: 'L320'
                    line_item_activity_code: 'A104'
                    line_item_description: 'Reviewing contract'
                    timekeeper_id: 102
                    timekeeper_first_name: 'Fiona'
                    timekeeper_last_name: 'Williams'
                    timekeeper_classsification: 'PARTNR'
                  - line_item_number: 45475
                    line_item_type: 'E'
                    line_item_unit_cost: '5000.00'
                    line_item_number_of_units: '1'
                    line_item_total: '5000.00'
                    line_item_currency: 'USD'
                    line_item_date: '20200218'
                    line_item_task_code: 'L320'
                    line_item_expense_code: 'X115'
                    line_item_description: 'Out of town travel - flights'

              required: [law_firm_matter_id, accrual_currency, accrual_net_total]
      responses:
        '200':    # status code
          description: Accrual updated correctly
        '404':
          description: Not Found. Matter could not be found.
        '501':
          description: 'Not implemented. For use if the server never supports the use of the discriminator provided, either law_firm_matter_id or client_matter_id.'
    delete:
      tags:
        - Accruals
      summary: Delete accruals for a matter
      description: Delete the accurals for a matter. The accrual figures should be set to null, not zero.
      parameters:
        - in: path
          name: client_matter_id
          schema:
            type: string
            description: the unique identifier for the matter, according to either the law firm system or client system.
      responses:
        '200':
          description: 'Accruals deleted.'
        '404':
          description: 'Matter not found.'
        '501':
          description: 'Not implemented. For use if the server never supports the use of the discriminator provided, either law_firm_matter_id or client_matter_id.'

tags:
  - name: Invoices
    description: Manage invoice data.
  - name: Accruals
    description: Manage accrual data; fees and expenses that have been recorded but not yet invoiced.
components:
  schemas:
    invoice_post:
      properties:
        ledes_format:
          $ref: '#/components/schemas/ledes_format'
        encrypted:
          $ref: '#/components/schemas/encrypted'
        ledes_filename:
          $ref: '#/components/schemas/ledes_filename'
        ledes_file_media_type:
          $ref: '#/components/schemas/ledes_file_media_type'
        invoice_type:
          $ref: '#/components/schemas/invoice_type'
        related_invoice_id:
          $ref: '#/components/schemas/related_invoice_id'
        comment:
          $ref: '#/components/schemas/comment'
      required:
      - ledes_format
      - encrypted
      - ledes_filename
      - ledes_file_media_type
      - invoice_type
    law_firm_matter_id:
      type: string
      description: The law firm assigned matter code, unique within that law firm's system.
      example: '873467'
    accrual_currency:
      type: string
      description: The currency for these accruals. The three-character ISO-4217 currency code.
    accrual_net_total:
      type: string
      description: The total accruals, net of any adjustments. This should be a string of numbers, followed by a decimal place, followed by two or four numbers depending on exponent (number of minor units) in the currency.
    fee_accrual_net_total:
      type: string
      description: The total of fees accrued, net of any adjustments. This should be a string of numbers, followed by a decimal place, followed by two or four numbers depending on exponent (number of minor units) in the currency.
    expense_accrual_net_total:
      type: string
      description: The total expenses accrued, net of any adjustments. This should be a string of numbers, followed by a decimal place, followed by two or four numbers depending on exponent (number of minor units) in the currency.
    monthly_accrual_net_total:
      type: object
      properties:
        month:
          type: string
          description: Calendar month in YYYYMM format.
        accrual_currency:
          $ref: '#/components/schemas/accrual_currency'
        accrual_net_total:
          $ref: '#/components/schemas/accrual_net_total'
        fee_accrual_net_total:
          $ref: '#/components/schemas/fee_accrual_net_total'
        expense_accrual_net_total:
          $ref: '#/components/schemas/expense_accrual_net_total'
      required:
       - month
       - accrual_currency
       - accrual_net_total
    accrual_line_item:
      type: object
    Expense:
      properties:
        line_item_number:
          type: string
          description: Unique identifier for this line item within the law firm.
          example: '181632'
        line_item_unit_cost:
          type: string
          description: The standard (i.e., undiscounted) unit cost, before taxes, of the line item. For fees, this would be the hourly rate. For expenses, this would be the cost per unit.
          example: 260.00
        line_item_number_of_units:
          type: string
          description: The number of units billed on this line item. For fee items, this is the number of hours being billed. For expense items, this is the number of items being expensed.
          example: 1.75
        line_item_adjustment_amount:
          type: string
          description: The numerical value of any adjustment applied to this line item. A positive value indicates a premium, a negative value indicates a discount. A null ("") or zero ("0") value indicates no adjustment.
          example: 0
        line_item_total:
          type: string
          description: The numerical value of this line item. This must be (line_item_unit_cost * line_item_number_of_units) + line_item_adjustment_amount. A null value ("") would be an error.
          example: 100.00
        line_item_currency:
          type: string
          description: The three-character ISO-4217 currency code for this line item.
          example: 'USD'
        line_item_date:
          type: string
          description: The date the fees/expenses were incurred, in YYYYMMDD format.
          example: '20191127'
        line_item_description:
          type: string
          description: Free form description of this line item, that provides specific detail beyond the expense code.
          example: 'Translaction services'
        line_item_task_code:
          type: string
          description: The task code (e.g., using the UTBMS code set) for this line item.
          example: L110
        line_item_type:
          type: string
          description: The type of line item. E - Expense. F - Fee.
          enum: [Fee, Expense]
        line_item_expense_code:
          type: string
          description: The expense code (e.g., using the UTBMS code set) for this expense line item.
          example: X139

      required: [line_item_number, line_item_type, line_item_total, line_item_date, line_item_unit_cost, line_item_number_of_units, line_item_expense_code]
    Fee:
      properties:
        line_item_number:
          type: string
          description: Unique identifier for this line item within the law firm.
          example: '181632'
        line_item_unit_cost:
          type: string
          description: The standard (i.e., undiscounted) unit cost, before taxes, of the line item. For fees, this would be the hourly rate. For expenses, this would be the cost per unit.
          example: 260.00
        line_item_number_of_units:
          type: string
          description: The number of units billed on this line item. For fee items, this is the number of hours being billed. For expense items, this is the number of items being expensed.
          example: 1.75
        line_item_adjustment_amount:
          type: string
          description: The numerical value of any adjustment applied to this line item. A positive value indicates a premium, a negative value indicates a discount. A null ("") or zero ("0") value indicates no adjustment.
          example: 0
        line_item_total:
          type: string
          description: The numerical value of this line item. This must be (line_item_unit_cost * line_item_number_of_units) + line_item_adjustment_amount. A null value ("") would be an error.
          example: 100.00
        line_item_currency:
          type: string
          description: The three-character ISO-4217 currency code for this line item.
          example: 'USD'
        line_item_date:
          type: string
          description: The date the fees/expenses were incurred, in YYYYMMDD format.
          example: '20191127'
        line_item_description:
          type: string
          description: Free form description of this line item.
          example: 'abc'
        line_item_task_code:
          type: string
          description: The task code (e.g., using the UTBMS code set) for this line item. 
          example: L101
        line_item_type:
          type: string
          description: The type of line item. E - Expense. F - Fee.
          enum: [Fee, Expense]
        line_item_activity_code:
          type: string
          description: The activity code (e.g., using the UTBMS code set) for this fee line item. Most expense items probably do not have a entry associated with them (in which case this field would be left null).
          example: A118
        timekeeper_id:
          type: string
          description: A unique identifier within the law firm for the timekeeper for this line entry.
          example: '1835'
        timekeeper_first_name:
          type: string
          description: The first name of a timekeeper.
          example: 'Robert'
        timekeeper_last_name:
          type: string
          description: The last name of a timekeeper.
          example: 'Amsley'
        timekeeper_classsification:
          type: string
          description: The staff classification of a timekeeper.  A full list of the codes to use can be found in the LEDES Revised Timekeeper Classifications Reference Document available on LEDES.org.
          example: 'PARTNR'
      required: [line_item_number, line_item_type, line_item_total, line_item_date, line_item_unit_cost, line_item_number_of_units]
    ledes_format:
      type: string
      description: The LEDES invoice file format
      enum:
      - LEDES98B
      - LEDES98BI
      - LEDES98BIV2
      - LEDES2000
      - LEDESXML20
      - LEDESXML21
      example: LEDES98BI
    encrypted:
      type: boolean
      description: Whether the ledesfile is encrypted or not.
      example: 'True'
    ledes_filename:
      type: string
      example: Invoice1234.234.xml
      description: The name of the LEDES file. This does not need to be unique or
        be the invoice number, which is a common filename for LEDES file. It can
        simply be the filename of the LEDES file on the sending system side for
        reference purposes. This should be the filename without mime type (ie. INV-2019-123).
        This should not include any network or folder path information. Receiving
        systems can set a limit for the length of filenames with the appropriate
        error message described below.
    ledes_file_media_type:
      type: string
      description: The LEDES invoice file format
      enum:
      - text/plain
      - text/csv
      example:
      - text/csv
    invoice_type:
      type: string
      description: The type of invoice being submitted.
      enum:
      - INVOICE
      - ACCRUAL
      - SHADOW
      - RESUBMIT
      - APPEAL
      - REPLACEMENT
      example:
      - INVOICE
    related_invoice_id:
      type: integer
      description: The Invoice ID of a related invoice that the submitted invoice
        is associated. For example, if an invoice is rejected and then a new invoice
        is submitted with adjustments or as an appeal, this would be the invoice
        ID of the originally submitted invoice. This is required for invoiceTypes
        of resubmit, appeal and replacement.
      example: 58912746
    invoice_status:
      type: string
      description: The status of the invoice
      enum:
      - RECEIVED
      - FILE_ERROR
      - PENDING_CLIENT
      - PENDING_TAX_AUTHORITY
      - PENDING_VENDOR
      - DELIVERED_TO_CLIENT
      - REJECTED
      - APPROVED
      - SENT_TO_AP
      - PAID
      example: 'RECEIVED'
    invoice_errors:
      type: array
      items:
        type: object
        properties:
          error_type:
            type: string
            enum:
            - FILE_STRUCTURE
            - MISSING_FIELD
            - BAD_FILE_DATA
            - INVOICE_LEVEL_ERROR
            - LINE_ITEM_ERROR
            - AUDIT_ERROR
            - AFA_ERROR
            example: "LINE_ITEM_ERROR"
          datetime:
            type: string
            description: The date and time of the error represented as an offest from UTC using ISO 8601.
            example: '2020-04-19T15:55:12Z'
          error_code:
            type: string
            example: "BD214"
          error_name:
            type: string
            example: 'Invalid Timekeeper'
          error_description:
            type: string
            example: 'Line item #6 has an invalid timekeeper ID: 12345.'
          line_item:
            $ref: '#/components/schemas/line_item'
    invoice_adjustments:
      type: array
      items:
        type: object
        properties:
          adjustment_type:
            type: string
            enum:
            - INVOICE_LEVEL_ADJUSTMENT
            - LINE_ITEM_ADJUSTMENT
            example: "LINE_ITEM_ADJUSTMENT"
          datetime:
            type: string
            description: The date and time the adjustment was identified.
            example: '2020-04-19T15:55:12+02:00'
          adjustment_amount:
            type: string
            example: "210.05"
          adjustment_currency:
            type: string
            example: 'USD'
          adjustment_reason:
            type: string
            example: 'Block billing guideline violation.'
          original_line_item:
            $ref: '#/components/schemas/line_item'
          adjusted_line_item:
            $ref: '#/components/schemas/line_item'
    line_item:
      properties:
        line_item_ref:
          type: string
          description: 'This is the line item number from the original LEDES file 
          and should be set if possible. This is the file_item_nbr field in LEDES XML 
          or the LINE_ITEM_NUMBER field in LEDES98B/BI. If the receiving system hasn’t 
          maintained the original LEDES line number reference, then a value of -9999 
          should be returned and the rest of the line item fields should be set for the 
          time & billing application to understand which line item is being referenced. 
          This property is not used when specifying a line item adjustment in the case of 
          InvoiceAdjustment.adjustedLineItem since the reference to the line item is specified 
          with InvoiceAdjustment.originalLineItem. Read only.'
          example: 5
        line_item_type:
          type: string
          description: The type of line item, either a fee (F) or an expense (E)
          enum:
          - F
          - E
          example: 'F'
    invoice_payments:
      type: array
      items:
        type: object
        properties:
          payment_type:
            type: string
            enum:
            - CHECK
            - WIRE
            - ACH
            - CREDIT_CARD
            example: "WIRE"
          datetime:
            type: string
            description: The date and time of the payment represented as an offest from UTC using ISO 8601.
            example: '2020-04-19T15:55:12-04:00'
          payment_amount:
            type: string
            example: "25000.00"
          payment_currency:
            type: string
            example: 'USD'
          payment_reference:
            type: string
            description: The reference information for the payment, for example, the check number. For Wire and ACH this should be the confirmation number. 
            example: '3384455'
          payee:
            type: string
            description: The entity to whom the payment was made.
            example: 'Moose and Squirrel.'
          paid_to_account:
            type: string
            description: The account to which the payment was made for paymentType’s of Wire, ACH, and Credit.
            example: '55778674'
    comment:
      type: string
      description: Description of the invoice.
      example:
      - 'Invoice for May 2020 for Matter 12345.'
  parameters:
    invoiceid:
      type: string
      description: The invoice id
      example: '7846859'



